name: Generate terraform docs
on:
  push:
    branches:
      - develop
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: develop

    - name: Render terraform docs inside the README.md and push changes back to branch
      uses: terraform-docs/gh-actions@v0.10.0
      with:
        working-dir: .
        output-file: README.md
        output-method: inject
        git-push: "true"
